name: Install and test

on:
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: windows-latest
    steps:
    
    - name: Get public nuse.bat
      run: |
        cd $userprofile
        curl https://raw.githubusercontent.com/vallyian/nuse/main/nuse.bat -o nuse.bat
        
    - name: Install
      run: |
        echo prevent script from pausing
        echo "" > pause.bat
        echo install nuse and node 14
        nuse 14

