name: Install and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  install-and-test:
    runs-on: windows-latest
    env:
      nuseDir: .
      debugger: "true"

    steps:
      - name: Disable built-in node.js
        shell: cmd
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          rename "%nodepath%" "node.exe.old"
          rename "%nodepath:node.exe=npm.cmd%" "npm.cmd.old"

      - name: Install node 16
        shell: cmd
        run: nuse.bat 16 ${debugger}

      - name: Test node 16
        shell: cmd
        working-directory: ${nuseDir}
        run: node-latest.exe test "16" "7"

      - name: Upgrade npm
        shell: cmd
        working-directory: ${nuseDir}
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          cd %nodepath:node.exe=%
          npm i npm@8

      - name: Test upgraded npm
        shell: cmd
        working-directory: ${nuseDir}
        run: node-latest.exe test "16" "7"

      - name: Install node 14
        shell: cmd
        working-directory: ${nuseDir}
        run: nuse.bat 14 ${debugger}

      - name: Test node 14
        shell: cmd
        working-directory: ${nuseDir}
        run: node-latest.exe test "14" "6"

      - name: Switch back to node 16
        shell: cmd
        working-directory: ${nuseDir}
        run: nuse.bat 18 ${debugger}

      - name: Test npm persistence
        shell: cmd
        working-directory: ${nuseDir}
        run: node-latest.exe test "16" "8"

      - name: Install 'gallium'
        shell: cmd
        working-directory: ${nuseDir}
        run: nuse.bat gallium ${debugger}

      - name: Test 'gallium'
        shell: cmd
        working-directory: ${nuseDir}
        run: node-latest.exe test "16" "8"
