name: Install and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  install-and-test:
    runs-on: windows-latest
    env:
      nuseDir: .

    steps:
      - name: Disable built-in node.js
        shell: cmd
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          rename "%nodepath%" "node.exe.old"
          rename "%nodepath:node.exe=npm.cmd%" "npm.cmd.old"

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install node 16
        shell: cmd
        run: nuse 16 true

      - name: Test node 16
        shell: cmd
        run: node-latest.exe test "16" "7"

      - name: Upgrade npm
        shell: cmd
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          cd %nodepath:node.exe=%
          npm i npm@8

      - name: Test upgraded npm
        shell: cmd
        run: node-latest.exe test "16" "7"

      - name: Install node 14
        shell: cmd
        run: nuse.bat 14 %debugger%

      - name: Test node 14
        shell: cmd
        run: node-latest.exe test "14" "6"

      - name: Switch back to node 16
        shell: cmd
        run: nuse.bat 18 %debugger%

      - name: Test npm persistence
        shell: cmd
        run: node-latest.exe test "16" "8"

      - name: Install 'gallium'
        shell: cmd
        run: nuse.bat gallium %debugger%

      - name: Test 'gallium'
        shell: cmd
        run: node-latest.exe test "16" "8"
