name: Install and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  install-and-test:
    runs-on: windows-latest
    steps:
      - name: Get public nuse.bat
        shell: cmd
        run: curl https://raw.githubusercontent.com/vallyian/nuse/main/nuse.bat -o nuse.bat

      - name: Install nuse and node 14
        shell: cmd
        run: nuse 14
