name: Install and test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  install-and-test:
    runs-on: windows-latest
    steps:
      - name: Disable built-in node.js
        shell: cmd
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          rename "%nodepath%" "node.exe.old"
          rename "%nodepath:node.exe=npm.cmd%" "npm.cmd.old"

      - name: Get public nuse.bat
        shell: cmd
        run: curl https://raw.githubusercontent.com/vallyian/nuse/main/nuse.bat -o nuse.bat

      - name: Install node 16
        shell: cmd
        run: nuse 16

      - name: Test node 16
        shell: cmd
        working-directory: $userprofile/.nuse
        run: node-latest.exe test "16" "7"

      - name: Upgrade npm
        shell: cmd
        working-directory: $userprofile/.nuse
        run: |
          for /F "tokens=*" %%x in ('where node') do (set nodepath=%%x)
          cd %nodepath:node.exe=%
          npm i npm@8

      - name: Test upgraded npm
        shell: cmd
        working-directory: $userprofile/.nuse
        run: node-latest.exe test "16" "7"

      - name: Install node 14
        shell: cmd
        working-directory: $userprofile/.nuse
        run: nuse 14

      - name: Test node 14
        shell: cmd
        working-directory: $userprofile/.nuse
        run: node-latest.exe test "14" "6"

      - name: Switch back to node 16
        shell: cmd
        working-directory: $userprofile/.nuse
        run: nuse 18

      - name: Test npm persistence
        shell: cmd
        working-directory: $userprofile/.nuse
        run: node-latest.exe test "16" "8"

      - name: Install 'gallium'
        shell: cmd
        working-directory: $userprofile/.nuse
        run: nuse gallium

      - name: Test 'gallium'
        shell: cmd
        working-directory: $userprofile/.nuse
        run: node-latest.exe test "16" "8"
